apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fargoflask
namePrefix: fargo
resources:
- ../../base
- ./namespace.yaml
patches:
- target:
    kind: SqlManagedInstance
    name: sql
  path: fargosql.yaml
- target:
    kind: Deployment
    name: flask2sql
  path: fargoapp.yaml
