- op: replace
  path: /spec/template/spec/containers/0/env/0/value
  value: akssql
- op: replace
  path: /spec/template/spec/containers/0/env/1/valueFrom/secretKeyRef/name
  value: aks-login-secret
- op: replace
  path: /spec/template/spec/containers/0/env/2/valueFrom/secretKeyRef/name
  value: aks-login-secret
- op: replace
  path: /spec/template/spec/initContainers/0/env/0/value
  value: akssql
- op: replace
  path: /spec/template/spec/initContainers/0/env/1/valueFrom/secretKeyRef/name
  value: aks-login-secret
- op: replace
  path: /spec/template/spec/initContainers/0/env/2/valueFrom/secretKeyRef/name
  value: aks-login-secret
