apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aksinazure
namePrefix: aks
resources:
- ../../base
- ./namespace.yaml
patches:
- target:
    kind: SqlManagedInstance
    name: sql
  path: sql.yaml
- target:
    kind: Deployment
    name: flask2sql
  path: app.yaml
